package entity;
// Generated 01-oct-2018 21:01:02 by Hibernate Tools 4.3.1



/**
 * Exercise generated by hbm2java
 */
public class Exercise  implements java.io.Serializable {


     private Integer idExercise;
     private Grupo grupo;
     private String level;
     private String name;
     private String stage;

    public Exercise() {
    }

	
    public Exercise(Grupo grupo) {
        this.grupo = grupo;
    }
    public Exercise(Grupo grupo, String level, String name, String stage) {
       this.grupo = grupo;
       this.level = level;
       this.name = name;
       this.stage = stage;
    }
   
    public Integer getIdExercise() {
        return this.idExercise;
    }
    
    public void setIdExercise(Integer idExercise) {
        this.idExercise = idExercise;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStage() {
        return this.stage;
    }
    
    public void setStage(String stage) {
        this.stage = stage;
    }




}


