package entity;
// Generated 01-oct-2018 21:01:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private Integer idGrupo;
     private String name;
     private Set studentGrupos = new HashSet(0);
     private Set teacherGrupos = new HashSet(0);
     private Exercise exercise;

    public Grupo() {
    }

    public Grupo(String name, Set studentGrupos, Set teacherGrupos, Exercise exercise) {
       this.name = name;
       this.studentGrupos = studentGrupos;
       this.teacherGrupos = teacherGrupos;
       this.exercise = exercise;
    }
   
    public Integer getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(Integer idGrupo) {
        this.idGrupo = idGrupo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getStudentGrupos() {
        return this.studentGrupos;
    }
    
    public void setStudentGrupos(Set studentGrupos) {
        this.studentGrupos = studentGrupos;
    }
    public Set getTeacherGrupos() {
        return this.teacherGrupos;
    }
    
    public void setTeacherGrupos(Set teacherGrupos) {
        this.teacherGrupos = teacherGrupos;
    }
    public Exercise getExercise() {
        return this.exercise;
    }
    
    public void setExercise(Exercise exercise) {
        this.exercise = exercise;
    }




}


