package entity;
// Generated 01-oct-2018 21:01:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private Integer idStudent;
     private Teacher teacher;
     private User user;
     private String email;
     private String password;
     private String firstName;
     private String lastName;
     private Set studentGrupos = new HashSet(0);

    public Student() {
    }

	
    public Student(Teacher teacher, User user) {
        this.teacher = teacher;
        this.user = user;
    }
    public Student(Teacher teacher, User user, String email, String password, String firstName, String lastName, Set studentGrupos) {
       this.teacher = teacher;
       this.user = user;
       this.email = email;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.studentGrupos = studentGrupos;
    }
   
    public Integer getIdStudent() {
        return this.idStudent;
    }
    
    public void setIdStudent(Integer idStudent) {
        this.idStudent = idStudent;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Set getStudentGrupos() {
        return this.studentGrupos;
    }
    
    public void setStudentGrupos(Set studentGrupos) {
        this.studentGrupos = studentGrupos;
    }




}


