package entity;
// Generated 01-oct-2018 21:01:02 by Hibernate Tools 4.3.1



/**
 * StudentGrupo generated by hbm2java
 */
public class StudentGrupo  implements java.io.Serializable {


     private StudentGrupoId id;
     private Grupo grupo;
     private Student student;

    public StudentGrupo() {
    }

    public StudentGrupo(StudentGrupoId id, Grupo grupo, Student student) {
       this.id = id;
       this.grupo = grupo;
       this.student = student;
    }
   
    public StudentGrupoId getId() {
        return this.id;
    }
    
    public void setId(StudentGrupoId id) {
        this.id = id;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }




}


