package entity;
// Generated 01-oct-2018 21:01:02 by Hibernate Tools 4.3.1



/**
 * StudentGrupoId generated by hbm2java
 */
public class StudentGrupoId  implements java.io.Serializable {


     private int idStudent;
     private int idGrupo;

    public StudentGrupoId() {
    }

    public StudentGrupoId(int idStudent, int idGrupo) {
       this.idStudent = idStudent;
       this.idGrupo = idGrupo;
    }
   
    public int getIdStudent() {
        return this.idStudent;
    }
    
    public void setIdStudent(int idStudent) {
        this.idStudent = idStudent;
    }
    public int getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(int idGrupo) {
        this.idGrupo = idGrupo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentGrupoId) ) return false;
		 StudentGrupoId castOther = ( StudentGrupoId ) other; 
         
		 return (this.getIdStudent()==castOther.getIdStudent())
 && (this.getIdGrupo()==castOther.getIdGrupo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdStudent();
         result = 37 * result + this.getIdGrupo();
         return result;
   }   


}


