package entity;
// Generated 01-oct-2018 21:01:02 by Hibernate Tools 4.3.1



/**
 * TeacherGrupo generated by hbm2java
 */
public class TeacherGrupo  implements java.io.Serializable {


     private TeacherGrupoId id;
     private Grupo grupo;
     private Teacher teacher;

    public TeacherGrupo() {
    }

    public TeacherGrupo(TeacherGrupoId id, Grupo grupo, Teacher teacher) {
       this.id = id;
       this.grupo = grupo;
       this.teacher = teacher;
    }
   
    public TeacherGrupoId getId() {
        return this.id;
    }
    
    public void setId(TeacherGrupoId id) {
        this.id = id;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }




}


