package entity;
// Generated 01-oct-2018 21:01:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher  implements java.io.Serializable {


     private Integer idTeacher;
     private User user;
     private String email;
     private String password;
     private String firstName;
     private String lastName;
     private Set teacherGrupos = new HashSet(0);
     private Student student;

    public Teacher() {
    }

	
    public Teacher(User user) {
        this.user = user;
    }
    public Teacher(User user, String email, String password, String firstName, String lastName, Set teacherGrupos, Student student) {
       this.user = user;
       this.email = email;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.teacherGrupos = teacherGrupos;
       this.student = student;
    }
   
    public Integer getIdTeacher() {
        return this.idTeacher;
    }
    
    public void setIdTeacher(Integer idTeacher) {
        this.idTeacher = idTeacher;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Set getTeacherGrupos() {
        return this.teacherGrupos;
    }
    
    public void setTeacherGrupos(Set teacherGrupos) {
        this.teacherGrupos = teacherGrupos;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }




}


