package entity;
// Generated 01-oct-2018 21:01:02 by Hibernate Tools 4.3.1



/**
 * TeacherGrupoId generated by hbm2java
 */
public class TeacherGrupoId  implements java.io.Serializable {


     private int idTeacher;
     private int idGrupo;

    public TeacherGrupoId() {
    }

    public TeacherGrupoId(int idTeacher, int idGrupo) {
       this.idTeacher = idTeacher;
       this.idGrupo = idGrupo;
    }
   
    public int getIdTeacher() {
        return this.idTeacher;
    }
    
    public void setIdTeacher(int idTeacher) {
        this.idTeacher = idTeacher;
    }
    public int getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(int idGrupo) {
        this.idGrupo = idGrupo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TeacherGrupoId) ) return false;
		 TeacherGrupoId castOther = ( TeacherGrupoId ) other; 
         
		 return (this.getIdTeacher()==castOther.getIdTeacher())
 && (this.getIdGrupo()==castOther.getIdGrupo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTeacher();
         result = 37 * result + this.getIdGrupo();
         return result;
   }   


}


